#!/usr/bin/env python3

###################################
# SALTED-REPORTCHECK SCRIPT       #
# Script to check for and display #
# contents of latency_report.txt  #
# and topdata.txt if found        #
# Created by Matthew Boucher      #
# 2024-05-22                      #
###################################

import os
import socket

def get_hostname():
    return socket.gethostname()

def nothing_to_report():
    print("Nothing to Report.")

def main():
    report_file_name = 'latency_report.txt'
    topdata_file_name = 'topdata.txt'
    report_found = False
    topdata_found = False

    if os.path.isfile(report_file_name):
        with open(report_file_name, 'r') as file:
            contents = file.read()
            print(contents)
        os.remove(report_file_name)
        report_found = True

    if os.path.isfile(topdata_file_name):
        with open(topdata_file_name, 'r') as file:
            contents = file.read()
            print(contents)
        os.remove(topdata_file_name)
        topdata_found = True

    if not report_found and not topdata_found:
        nothing_to_report()

if __name__ == "__main__":
    main()

