#!/usr/bin/env python3

###########################################################
# PYTHONCHECK SCRIPT                                      #
# This script checks and displays the Python version.    #
# Created by Matthew Boucher on 2024-04-03                #
###########################################################

import sys

def check_python_version():
    """Prints the current Python version."""
    print("Current Python version:", sys.version)

if __name__ == "__main__":
    check_python_version()

