#!/usr/bin/env python3

###################################
#        SALTED-TOPCPU SCRIPT     #
#   Monitors top CPU processes    #
#  created by Matthew Boucher     #
#           2024-05-26            #
###################################

import time
import subprocess

def get_top_cpu_processes():
    result = subprocess.run(
        ['ps', 'aux', '--sort=-%cpu', '|', 'head', '-n', '10'],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        universal_newlines=True
    )
    return result.stdout

start_time = time.time()
while time.time() - start_time < 30:
    print(get_top_cpu_processes())
    time.sleep(5)

